development:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: isamba
    pool: 5
    username: root
    password: root
    #socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: isamba
    pool: 5
    username: root
    password: root
    #socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: isamba
    pool: 5
    username: root
    password: root
    #socket: /Applications/MAMP/tmp/mysql/mysql.sock

